## [특강] Numpy, Pandas, Matplotlib

### 2. Pandas 기본 구조: Series와 DataFrame

#### 2.1 Series와 DataFrame
Series

- 1차원 구조체

In [1]:
import pandas as pd

In [3]:
scores = pd.Series([90, 85, 88])

scores, type(scores)

(0    90
 1    85
 2    88
 dtype: int64,
 pandas.Series)

DataFrame

- 2차원(행, 열) 구조체

In [14]:
data = {
    "이름": ['김철수', '이영희', "박민수"],
    "부서": ["개발", "기획", "개발"],
    "급여": [4500, 5200, 48000]
}

df = pd.DataFrame(data)

df

    이름  부서     급여
0  김철수  개발   4500
1  이영희  기획   5200
2  박민수  개발  48000

#### 2.2 데이터 탐색 속성(shape, dtypes)과 진단(info, describe)

- 탐색적 데이터 분석(EDA)
- df.info()
    - 누락치 확인(Non-Null Count)
    - dtype: 통계가 가능한 자료형인지 체크(잘못된 데이터가 있는지 여부 확인 -> 치환 -> 자료형 변환)
- df.describe()
    - 평균, 중앙값, 최대, 최소값을 통해서 이상치(극단치)를 확인

In [10]:
print("df.info()")
df.info()

df.info()
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      str
 1   부서      3 non-null      str
 2   급여      3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [15]:
df.describe()

                 급여
count      3.000000
mean   19233.333333
std    24915.122583
min     4500.000000
25%     4850.000000
50%     5200.000000
75%    26600.000000
max    48000.000000

#### 2.3 데이터 변경 및 인덱스 제어(set_index, reset_index)

In [18]:
#df['급여'], type(df['급여'])
df['보너스'] = df['급여'] * 0.1

df

    이름  부서     급여     보너스
0  김철수  개발   4500   450.0
1  이영희  기획   5200   520.0
2  박민수  개발  48000  4800.0

In [19]:
# 인덱스를 변경
df_indexed = df.set_index('이름')

df_indexed

     부서     급여     보너스
이름
김철수  개발   4500   450.0
이영희  기획   5200   520.0
박민수  개발  48000  4800.0

In [20]:
# 인덱스를 다시 숫자형 인덱스로 변경
df_restored = df_indexed.reset_index()

df_restored

    이름  부서     급여     보너스
0  김철수  개발   4500   450.0
1  이영희  기획   5200   520.0
2  박민수  개발  48000  4800.0

#### 2.4 Pandas Series & DataFrame 브로드캐스팅 연산

- axis : 0 -> 행의 인덱스 기준
- axis : 1 -> 컬럼 기준

In [24]:
df = pd.DataFrame({
    '중간고사': [80, 95, 70],
    '기말고사': [85, 90, 75]
}, index=['김철수', '이영희', '박민수'])

df

     중간고사  기말고사
김철수    80    85
이영희    95    90
박민수    70    75

In [25]:
score_means = df.mean(axis=0) # 행 기준 (인덱스 기준)
score_means

중간고사    81.666667
기말고사    83.333333
dtype: float64

In [26]:
score_gap = df.sub(score_means, axis=1)

score_gap

          중간고사      기말고사
김철수  -1.666667  1.666667
이영희  13.333333  6.666667
박민수 -11.666667 -8.333333

### 3. Pandas 정밀 조회 및 결측치 제어

#### 3.1  loc와 iloc를 활용한 행·열 선택

#### 3.2 불리언 인덱싱과 query() 조건 검색

불리언 인덱싱

query() 필터링

#### 3.3 결측치(Missing Data) 7대 처리 기법
3.3.1 결측치 탐지 및 현황 요약 (Detection)

3.3.2 결측치 삭제 (Drop)

3.3.3 통계적 대푯값 대치 (Imputation)

3.3.4 시계열 직전/직후 값 대치 (Forward / Backward Fill)

3.3.5 선형 보간법 (Linear Interpolation)

3.3.6 이상 기호 치환 및 수치형 변환 (Replace & Type Casting)

3.3.7 결측 여부 지표 변수 생성 (Missing Indicator)

#### 3.4 그룹화 집계(groupby)와 .to_numpy() 상호 변환